services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-app:latest
    container_name: ecommerce-app
    environment:
      DB_HOST: mysql
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: ecommerce
      MYSQL_DB: ecommerce_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_PORT: 9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    depends_on:
      - mysql
      - redis
      - minio
    ports:
      - "8080:8080"
    restart: on-failure

  redis:
    image: redis:7
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: ecommerce-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  mysql_data:
  redis_data:
  minio_data:
